export default{
    result:'',
    department_list:[],
    return_award_data:[],
    leave_employee_data:[],
    rate_data:[],
    award_data : [],
    day_list:[],
    role_data:[],
    rank_data:[],
    employee_data_shift:[],
    training_list:[],
    training_list_data : [],
    unit_data : [],
    rule_data : [],
    rank_data : [],
    service_performance_data:[
        {no : 1 ,
            name : "Thian Lian Ben" , 
            date : '2019-04-21',
            work_done : "Android Projects" ,
            remarks : "this project is Women Safety"},
            {no : 2 ,
            name : "Thawzin Oo" , 
            date : '2019-12-04',
            work_done : "Android Projects" ,
            remarks : "this project is Hacking"}
    ],
    product_performance_data:[
        { no :1 ,
            employee_name : "John Smith" , 
            unit : "Fix the bottle",
            date : '2018-09-12',
            price : "400" ,
            finish : "3" ,
            amount : "5000"},
            { no :12 ,
                employee_name : "Thian Lian Ben" , 
                unit : "Fix the bottle",
                date : '2018-10-21',
                price : "80" ,
                finish : "3" ,
                amount : "400"}
        
    ],
    employee_data_detail_for_dialog:[],
    employee_cv_form:[],
    department_detail:[],
    branch_data_detail:[],
    employee_list:[],
    employee_data_attendance:[
        { no : 1 , day:'1',month:'1',year:'2019' ,employee_number: "FT-20293" , employee_name : "Thian Lian Ben" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 2 , day:'1',month:'1',year:'2019' ,employee_number: "FT-30093" , employee_name : "Aung Nai Oo" , start_time: "06:30 AM" , end_time: "11:00 AM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" , remarks : "30 mins" , start_time_disable : true , end_time_disable : true ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 3 , day:'1',month:'1',year:'2019' ,employee_number: "FT-90993" , employee_name : "Thawzin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 4 , day:'1',month:'1',year:'2019' , employee_number: "FT-09789" , employee_name : "Thura Aung" , start_time: "09:13 AM" , end_time: "18:00 PM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "present" ,icon:'done', remarks : "" , start_time_disable : true , end_time_disable : true ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 5 , day:'1',month:'1',year:'2019' ,employee_number: "FT-77774" , employee_name : "Zin Mar Myint" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 6 , day:'1',month:'1',year:'2019' ,employee_number: "FT-08063" , employee_name : "Mi Ni ang" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 7 , day:'1',month:'1',year:'2019',employee_number: "FT-08642" , employee_name : "Hang Ki Htut" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 8 , day:'1',month:'1',year:'2019' ,employee_number: "FT-20657" , employee_name : "Kim Jin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 9 , day:'1',month:'1',year:'2019' ,employee_number: "FT-37392" , employee_name : "Lee Min Hoo" , start_time: "06:18 AM" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'done', remarks : "18 mins" , start_time_disable : true , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 10 , day:'2',month:'1',year:'2019' ,employee_number: "emp1" , employee_name : "Thian Lian Ben" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 12 , day:'2',month:'1',year:'2019' ,employee_number: "emp2" , employee_name : "Aung Nai Oo" , start_time: "06:30 AM" , end_time: "11:00 AM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'done', remarks : "30 mins" , start_time_disable : true , end_time_disable : true ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 13 , day:'2',month:'1',year:'2019' ,employee_number: "emp3" , employee_name : "Thawzin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 14 , day:'2',month:'1',year:'2019' , employee_number: "emp4" , employee_name : "Thura Aung" , start_time: "09:13 AM" , end_time: "18:00 PM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "present" , icon:'done', remarks : "" , start_time_disable : true , end_time_disable : true ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 15 , day:'2',month:'1',year:'2019' ,employee_number: "emp5" , employee_name : "Zin Mar Myint" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 16 , day:'2',month:'1',year:'2019' ,employee_number: "emp6" , employee_name : "Mi Ni ang" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 17 , day:'2',month:'1',year:'2019',employee_number: "emp7" , employee_name : "Hang Ki Htut" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 18 , day:'2',month:'1',year:'2019' ,employee_number: "emp8" , employee_name : "Kim Jin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 19 , day:'2',month:'1',year:'2019' ,employee_number: "emp9" , employee_name : "Lee Min Hoo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 20 , day:'3',month:'1',year:'2019' ,employee_number: "emp1" , employee_name : "Thian Lian Ben" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 21 , day:'3',month:'1',year:'2019' ,employee_number: "emp2" , employee_name : "Aung Nai Oo" , start_time: "06:30 AM" , end_time: "11:00 AM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" , icon:'done',remarks : "30 mins" , start_time_disable : true , end_time_disable : true ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 22 , day:'3',month:'1',year:'2019' ,employee_number: "emp3" , employee_name : "Thawzin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 23 , day:'3',month:'1',year:'2019' , employee_number: "emp4" , employee_name : "Thura Aung" , start_time: "09:13 AM" , end_time: "18:00 PM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "present" ,icon:'done', remarks : "" , start_time_disable : true , end_time_disable : true ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 24 , day:'3',month:'1',year:'2019' ,employee_number: "emp5" , employee_name : "Zin Mar Myint" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 25 , day:'3',month:'1',year:'2019' ,employee_number: "emp6" , employee_name : "Mi Ni ang" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 26 , day:'3',month:'1',year:'2019',employee_number: "emp7" , employee_name : "Hang Ki Htut" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 27 , day:'3',month:'1',year:'2019' ,employee_number: "emp8" , employee_name : "Kim Jin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 29 , day:'3',month:'1',year:'2019' ,employee_number: "emp9" , employee_name : "Lee Min Hoo" , start_time: "06:18 AM" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'done', remarks : "18 mins" , start_time_disable : true , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 30 , day:'4',month:'1',year:'2019' ,employee_number: "emp1" , employee_name : "Thian Lian Ben" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 31 , day:'4',month:'1',year:'2019' ,employee_number: "emp2" , employee_name : "Aung Nai Oo" , start_time: "06:30 AM" , end_time: "11:00 AM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'done', remarks : "30 mins" , start_time_disable : true , end_time_disable : true ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 32 , day:'4',month:'1',year:'2019' ,employee_number: "emp3" , employee_name : "Thawzin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 33 , day:'4',month:'1',year:'2019' , employee_number: "emp4" , employee_name : "Thura Aung" , start_time: "09:13 AM" , end_time: "18:00 PM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "present" ,icon:'done', remarks : "" , start_time_disable : true , end_time_disable : true ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 34 , day:'4',month:'1',year:'2019' ,employee_number: "emp5" , employee_name : "Zin Mar Myint" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 35 , day:'4',month:'1',year:'2019' ,employee_number: "emp6" , employee_name : "Mi Ni ang" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 36 , day:'4',month:'1',year:'2019',employee_number: "emp7" , employee_name : "Hang Ki Htut" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 37 , day:'4',month:'1',year:'2019' ,employee_number: "emp8" , employee_name : "Kim Jin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 38 , day:'4',month:'1',year:'2019' ,employee_number: "emp9" , employee_name : "Lee Min Hoo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 39 , day:'1',month:'2',year:'2019' ,employee_number: "emp1" , employee_name : "Thian Lian Ben" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 40 , day:'1',month:'2',year:'2019' ,employee_number: "emp2" , employee_name : "Aung Nai Oo" , start_time: "06:30 AM" , end_time: "11:00 AM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'done', remarks : "30 mins" , start_time_disable : true , end_time_disable : true ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 41, day:'1',month:'2',year:'2019' ,employee_number: "emp3" , employee_name : "Thawzin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 42 , day:'1',month:'2',year:'2019' , employee_number: "emp4" , employee_name : "Thura Aung" , start_time: "09:13 AM" , end_time: "18:00 PM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "present" ,icon:'done', remarks : "" , start_time_disable : true , end_time_disable : true ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 5 , day:'1',month:'2',year:'2019' ,employee_number: "emp5" , employee_name : "Zin Mar Myint" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 6 , day:'1',month:'2',year:'2019' ,employee_number: "emp6" , employee_name : "Mi Ni ang" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 7 , day:'1',month:'2',year:'2019',employee_number: "emp7" , employee_name : "Hang Ki Htut" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 8 , day:'1',month:'2',year:'2019' ,employee_number: "emp8" , employee_name : "Kim Jin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 9 , day:'1',month:'2',year:'2019' ,employee_number: "emp9" , employee_name : "Lee Min Hoo" , start_time: "06:18 AM" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'done', remarks : "18 mins" , start_time_disable : true , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 10 , day:'2',month:'2',year:'2019' ,employee_number: "emp1" , employee_name : "Thian Lian Ben" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 12 , day:'2',month:'2',year:'2019' ,employee_number: "emp2" , employee_name : "Aung Nai Oo" , start_time: "06:30 AM" , end_time: "11:00 AM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'done', remarks : "30 mins" , start_time_disable : true , end_time_disable : true ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 13 , day:'2',month:'2',year:'2019' ,employee_number: "emp3" , employee_name : "Thawzin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 14 , day:'2',month:'2',year:'2019' , employee_number: "emp4" , employee_name : "Thura Aung" , start_time: "09:13 AM" , end_time: "18:00 PM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "present" ,icon:'done', remarks : "" , start_time_disable : true , end_time_disable : true ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 15 , day:'2',month:'2',year:'2019' ,employee_number: "emp5" , employee_name : "Zin Mar Myint" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 16 , day:'2',month:'2',year:'2019' ,employee_number: "emp6" , employee_name : "Mi Ni ang" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 17 , day:'2',month:'2',year:'2019',employee_number: "emp7" , employee_name : "Hang Ki Htut" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 18 , day:'2',month:'2',year:'2019' ,employee_number: "emp8" , employee_name : "Kim Jin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 19 , day:'2',month:'2',year:'2019' ,employee_number: "emp9" , employee_name : "Lee Min Hoo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 20 , day:'3',month:'2',year:'2019' ,employee_number: "emp1" , employee_name : "Thian Lian Ben" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 21 , day:'3',month:'2',year:'2019' ,employee_number: "emp2" , employee_name : "Aung Nai Oo" , start_time: "06:30 AM" , end_time: "11:00 AM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'done', remarks : "30 mins" , start_time_disable : true , end_time_disable : true ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 22 , day:'3',month:'2',year:'2019' ,employee_number: "emp3" , employee_name : "Thawzin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 23 , day:'3',month:'2',year:'2019' , employee_number: "emp4" , employee_name : "Thura Aung" , start_time: "09:13 AM" , end_time: "18:00 PM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "present" ,icon:'done', remarks : "" , start_time_disable : true , end_time_disable : true ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 24 , day:'3',month:'2',year:'2019' ,employee_number: "emp5" , employee_name : "Zin Mar Myint" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 25 , day:'3',month:'2',year:'2019' ,employee_number: "emp6" , employee_name : "Mi Ni ang" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 26 , day:'3',month:'2',year:'2019',employee_number: "emp7" , employee_name : "Hang Ki Htut" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 27 , day:'3',month:'2',year:'2019' ,employee_number: "emp8" , employee_name : "Kim Jin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 29 , day:'3',month:'2',year:'2019' ,employee_number: "emp9" , employee_name : "Lee Min Hoo" , start_time: "06:18 AM" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'clear', remarks : "18 mins" , start_time_disable : true , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 30 , day:'4',month:'2',year:'2019' ,employee_number: "emp1" , employee_name : "Thian Lian Ben" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 31 , day:'4',month:'2',year:'2019' ,employee_number: "emp2" , employee_name : "Aung Nai Oo" , start_time: "06:30 AM" , end_time: "11:00 AM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "late" ,icon:'done', remarks : "30 mins" , start_time_disable : true , end_time_disable : true ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 32 , day:'4',month:'2',year:'2019' ,employee_number: "emp3" , employee_name : "Thawzin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 33 , day:'4',month:'2',year:'2019' , employee_number: "emp4" , employee_name : "Thura Aung" , start_time: "09:13 AM" , end_time: "18:00 PM" , location : "MICT Park, Building(14) , Kanaunghub" , status : "present" ,icon:'done', remarks : "" , start_time_disable : true , end_time_disable : true ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 34 , day:'4',month:'2',year:'2019' ,employee_number: "emp5" , employee_name : "Zin Mar Myint" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 35 , day:'4',month:'2',year:'2019' ,employee_number: "emp6" , employee_name : "Mi Ni ang" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "18:00 PM" , duty_end_time : "23:00 PM" },
        { no : 36 , day:'4',month:'2',year:'2019',employee_number: "emp7" , employee_name : "Hang Ki Htut" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "09:00 AM" , duty_end_time : "18:00 PM" },
        { no : 37 , day:'4',month:'2',year:'2019' ,employee_number: "emp8" , employee_name : "Kim Jin Oo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" , icon:'clear',remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
        { no : 38 , day:'4',month:'2',year:'2019' ,employee_number: "emp9" , employee_name : "Lee Min Hoo" , start_time: "Start Time" , end_time: "End Time" , location : "MICT Park, Building(14) , Kanaunghub" , status : "absence" ,icon:'clear', remarks : "" , start_time_disable : false , end_time_disable : false ,duty_start_time : "06:00 AM" , duty_end_time : "11:00 AM" },
    ],
    branch_detail:[],
    department_name:'',
    branch_list:[],
    employee_data_detail:[],
    employee_data_details:[],
    leave_type_list:[],
    employee_role_list:[
        'CEO',
        'Manager'
    ],
    employee_state:[
        'Employee state',
        'Others'
    ],
    religion_list:[
        'Buddhism',
        'Christian'
    ],
    nationality_list:[
        'Burmese',
        'UK'
    ],
    city_list:[],
    township_list:[],
    region_list:[
        'Yangon',
        'Mandaly',
        'Banmaw',
        'Lashio'
    ],
    country_list:[
        'Myanmar',
        'China',
        'Japan',
        'India'
    ],
    marital_status_list:[
        'Single',
        'Relationship'
    ],
    shift_list:[],
    shfit_data:[],
    announcement_data:[]
}